apiVersion: apps/v1
kind: Deployment
metadata:
  name: goodayemate-backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: goodayemate-backend
  template:
    metadata:
      labels:
        app: goodayemate-backend
    spec:
      containers:
      - name: backend
        image: jamielabed/goodayemate-backend:latest
        ports:
        - containerPort: 8000
        env:
        - name: OPENAI_API_KEY
          valueFrom:
            secretKeyRef:
              name: openai-api-key
              key: api-key
      imagePullSecrets:
      - name: dockerhub-secret
---
apiVersion: v1
kind: Service
metadata:
  name: goodayemate-backend
spec:
  selector:
    app: goodayemate-backend
  ports:
  - protocol: TCP
    port: 8000
    targetPort: 8000
  type: ClusterIP